import { getGeminiClient } from "../gemini-server";
import { DEMO_PRODUCTS } from "@/data/demo-products";
import { DEMO_INVOICES } from "@/data/demo-invoices";
import { AgentRunResult, AgentAction } from "./types";
import { addAgentLog } from "./registry";

export async function runMarketingAgent(customPrompt?: string): Promise<AgentRunResult> {
  const overstockedProducts = DEMO_PRODUCTS.filter(p => p.stockStatus === "overstock");
  const highMarginProducts = DEMO_PRODUCTS.filter(p => {
    const margin = ((p.sellingPrice - p.costPrice) / p.sellingPrice) * 100;
    return margin >= 40;
  });

  const uniqueContractors = Array.from(
    new Set(
      DEMO_INVOICES.filter(i => i.type === "receivable").map(i => i.entityName)
    )
  );

  const marketingContext = {
    businessName: "Welcome Paint Center (NEXUS ERP)",
    targetAudience: {
      registeredContractorsCount: uniqueContractors.length > 0 ? uniqueContractors.length : 18,
      contractorNames: uniqueContractors,
      retailWalkInsAvgMonthly: 420,
    },
    overstockedClearanceCandidates: overstockedProducts.map(p => ({
      name: p.name,
      sku: p.sku,
      currentStock: p.currentStock,
      sellingPriceZAR: p.sellingPrice,
      costPriceZAR: p.costPrice,
    })),
    highMarginFocusLines: highMarginProducts.map(p => ({
      name: p.name,
      sku: p.sku,
      sellingPriceZAR: p.sellingPrice,
      marginPct: Math.round(((p.sellingPrice - p.costPrice) / p.sellingPrice) * 100),
    })),
    activeChannels: ["Email Campaigns", "SMS Broadcasts", "In-Store POS Banners", "WhatsApp Contractor Community"],
  };

  const ai = getGeminiClient();
  let insightsMarkdown = "";
  let source = "KDOS Autonomous Marketing Engine";

  if (ai) {
    try {
      const prompt = `
You are the KDOS Self-Marketing & Campaign Agent for NEXUS Enterprise ERP/POS.
Enterprise Commercial & Inventory Context:
${JSON.stringify(marketingContext, null, 2)}

User Instruction: "${customPrompt || "Design a high-ROI multi-channel marketing campaign targeting commercial trade contractors and clearance of overstocked enamel primers with email & WhatsApp copy"}"

Provide an actionable, structured marketing plan in Markdown format:
1. Executive Campaign Strategy & Value Proposition (Campaign name, objective, target audience)
2. Promotional Pricing & Product Pairing (Pairing high-margin acrylics with clearance primers)
3. Ready-to-Send Email & WhatsApp Broadcast Copy (Compelling hooks, CTA, clear ZAR pricing)
4. Conversion & ROI Forecast (Estimated reach, conversion rate, revenue uplift, capital unlocked)
5. Automated Follow-up Sequence for Sales Reps
`;
      const response = await ai.models.generateContent({
        model: "gemini-3.7-flash",
        contents: prompt,
      });

      if (response.text) {
        insightsMarkdown = response.text;
        source = "Gemini 3.7 Flash";
      }
    } catch {
      // Fallback
    }
  }

  if (!insightsMarkdown) {
    insightsMarkdown = `### **KDOS Autonomous Marketing Intelligence Briefing**
*Generated by NEXUS Self-Marketing Engine (Automated Rule System)*

#### **1. Recommended Active Campaign: "Spring Commercial Contractor Coat & Seal Special"**
- **Objective**: Accelerate inventory velocity on overstocked *Rust-Oleum Metal Primer* (67 units) while driving bulk purchases of high-margin *Dulux Weathershield 20L*.
- **Target Audience**: 18 registered commercial paint contractors & residential renovation firms.
- **Estimated Reach**: 180 verified trade contacts via SMS/WhatsApp & In-Store Till display.

#### **2. Campaign Mechanics & Bundled Offers**
- **Bundle Promo**: Buy 3x *Dulux Weathershield 20L* (R1,850 ea) and get **2x Rust-Oleum Metal Primers at 25% Off (R183.75 ea)**.
- **Contractor Perk**: Free job-site delivery on orders exceeding R5,000 within a 25km radius.

#### **3. Ready-to-Send Contractor Broadcast Copy**
\`\`\`text
[WHATSAPP / SMS BROADCAST]
Hi [Contractor Name], Welcome Paint Center Trade Desk here! 
Exclusive this week for our trade partners:
Get 25% OFF Rust-Oleum Metal Primers when you stock up on Dulux Weathershield 20L bulk drums.
Stock up for your upcoming job sites.
Reply 'QUOTE' to hold stock or call your trade rep directly.
T&Cs apply. Valid while warehouse stock lasts.
\`\`\`

#### **4. Projected Campaign ROI & Velocity**
- **Estimated Conversion**: 22% of targeted contractor accounts (approx. 4–6 bulk orders).
- **Projected Revenue Uplift**: **+R48,500** in trade sales over 10 days.
- **Trapped Capital Unlocked**: **R8,900** in surplus primer stock liquidated.`;
  }

  const suggestedActions: AgentAction[] = [
    {
      id: "act-mkt-" + Date.now(),
      agentId: "marketing",
      title: "Launch Contractor WhatsApp & Email Blast: Primer Clearance Special",
      description: "Dispatch automated WhatsApp & Email campaign to 18 registered trade contractors promoting 25% discount on overstocked Rust-Oleum Metal Primer with Dulux bulk drums.",
      category: "campaign_launch",
      severity: "medium",
      estimatedImpact: "Projected R48,500 trade revenue & R8,900 overstock capital recovery",
      payload: {
        campaignName: "Contractor Primer Clearance Special",
        channels: ["WhatsApp Broadcast", "Direct Email", "POS Counter Display"],
        targetAudience: "Tier 1 & Tier 2 Trade Contractors (18 accounts)",
        discountRate: "25% on Primer when bundled with 20L Weathershield",
        scheduledLaunch: "Immediate upon executive approval",
      },
      status: "pending_approval",
      createdAt: new Date().toISOString(),
    },
  ];

  addAgentLog({
    agentId: "marketing",
    agentName: "Self-Marketing & Campaign Agent",
    level: "action",
    message: "Formulated 'Spring Contractor Coat & Seal' campaign. Awaiting approval to dispatch.",
    details: { estimatedRevenueZAR: 48500, targetAccounts: 18 },
  });

  return {
    agentId: "marketing",
    agentName: "Self-Marketing & Campaign Agent",
    summary: "Formulated high-ROI contractor promotional campaign to liquidate surplus primer stock while boosting trade drum sales.",
    confidenceScore: 94,
    healthStatus: "optimal",
    keyFindings: [
      "Targeted campaign unlocks R8,900 in idle working capital from overstocked metal primer lines.",
      "Bundling with high-margin (44%) exterior paint protects overall gross profit margin above 38%.",
      "Drafted omni-channel SMS/WhatsApp broadcast with 1-click execution ready for approval.",
    ],
    suggestedActions,
    rawInsightsMarkdown: insightsMarkdown,
    timestamp: new Date().toISOString(),
    source,
  };
}
