import { getGeminiClient } from "../gemini-server";
import { DEMO_PRODUCTS } from "@/data/demo-products";
import { AgentRunResult, AgentAction } from "./types";
import { addAgentLog } from "./registry";

export interface SocialPostDraft {
  id: string;
  platform: "instagram" | "facebook" | "linkedin" | "google_business" | "tiktok";
  headline: string;
  copy: string;
  hashtags: string[];
  recommendedTime: string;
  mediaType: "image" | "carousel" | "video_script";
  mediaSuggestion: string;
  targetObjective: string;
}

export async function runSocialAgent(customPrompt?: string): Promise<AgentRunResult> {
  const featuredProducts = DEMO_PRODUCTS.slice(0, 4);

  const socialContext = {
    businessName: "Welcome Paint Center",
    tagline: "Your Premier Paint & Protective Coatings Supplier",
    location: "Johannesburg / Sandton / Durban, South Africa",
    topProducts: featuredProducts.map(p => ({
      name: p.name,
      category: p.categoryName || p.categoryId,
      brand: p.brandName || p.brandId,
      priceZAR: p.sellingPrice,
      sellingPoints: p.description,
    })),
    audienceSegments: [
      "Residential Homeowners & DIY Enthusiasts",
      "Professional Painting Contractors & Renovators",
      "Commercial Property Managers & Quantity Surveyors",
    ],
  };

  const ai = getGeminiClient();
  let insightsMarkdown = "";
  let source = "KDOS Autonomous Social Media Engine";

  if (ai) {
    try {
      const prompt = `
You are the KDOS Social Media Content & Engagement Agent for NEXUS Enterprise ERP/POS.
Business Profile & Products:
${JSON.stringify(socialContext, null, 2)}

User Instruction: "${customPrompt || "Generate a complete 7-day multi-channel social media schedule featuring high-performance paint products, contractor showcases, and local SEO Google Business posts with hashtags"}"

Provide an engaging, professional social media plan in Markdown format:
1. Executive Content Calendar & Channel Strategy (Instagram, Facebook, LinkedIn, Google Business)
2. Detailed Ready-to-Publish Posts (Headline, Full Caption with emojis, Call-To-Action, Hashtags, and Best Posting Time in SAST)
3. Visual Creative Direction & Photography Prompts for each post
4. Engagement & Community Growth Tactics (Story polls, contractor mentions, direct message automation)
5. Metric KPIs (Expected reach, click-through rate to POS/storefront, contractor inquiry velocity)
`;
      const response = await ai.models.generateContent({
        model: "gemini-3.7-flash",
        contents: prompt,
      });

      if (response.text) {
        insightsMarkdown = response.text;
        source = "Gemini 3.7 Flash";
      }
    } catch {
      // Fallback
    }
  }

  if (!insightsMarkdown) {
    insightsMarkdown = `### **KDOS Autonomous Social Media & Community Briefing**
*Generated by NEXUS Social Media Engine (Automated Content Planner)*

#### **1. Multi-Platform 7-Day Social Calendar**

##### **Post 1 — Instagram & Facebook: Product Showcase & Durability Test**
- **Platform**: Instagram / Facebook (Feed & Story)
- **Time**: Tuesday, 08:30 SAST (Peak morning contractor browsing)
- **Caption**:
  > 🌧️ Is your exterior coating ready for the Highveld summer storm season?
  > 
  > Protect your property with **Dulux Weathershield 20L** — engineered with Maxiflex technology for crack-resistance and superior UV defense. 
  > 
  > 🏢 Visit our Sandton Trade Counter or order via trade account today.
  > 🏷️ Price: **R 1,850.00 incl. VAT** (Bulk contractor rates available upon request).
  > 
  > 📍 Sandton & Durban Central | 🚚 Same-Day Site Delivery Available
- **Creative**: High-contrast split photo of weathered vs freshly coated exterior wall with water-beading effect.
- **Hashtags**: \`#DuluxSA #ExteriorPaint #ContractorsSA #JohannesburgConstruction #WeatherproofHome #WelcomePaintCenter #SouthAfricaRenovation\`

---

##### **Post 2 — LinkedIn: B2B Commercial Coating Case Study**
- **Platform**: LinkedIn (Company Page & Trade Reps)
- **Time**: Wednesday, 11:45 SAST
- **Caption**:
  > 🏗️ Delivering reliability on commercial scale projects.
  > 
  > When working on high-traffic commercial developments, drying times and industrial adhesion are non-negotiable. Our trade desk supplies complete specs from **Plascon Velvaglo Polyurethane Enamels** to specialised metal primers directly to site.
  > 
  > 📊 Open a 30-day NEXUS Commercial Trade Account today for preferential volume pricing and consolidated monthly SARS e-Tax invoicing.
- **Creative**: Carousel presentation on "3 Costly Mistakes in Commercial Wall Primer Specification".
- **Hashtags**: \`#CommercialArchitecture #QuantitySurveyorSA #FacilityManagement #BuildingMaterials #PaintContractorSA #NEXUSERP\`

---

##### **Post 3 — Google Business Profile: Local Search & Store Walk-In Drive**
- **Platform**: Google Business Profile (Local SEO Update)
- **Time**: Friday, 07:00 SAST
- **Caption**:
  > 🎨 Need custom tinting done fast before the weekend rush?
  > 
  > Our automated computerized paint tinting lab at Sandton Central matches any RAL, Pantone, or Dulux colour swatch in under 3 minutes.
  > 
  > Stop by today for expert colour advice and contractor supplies!
- **Call-to-Action**: *Get Directions / Call Now*`;
  }

  const suggestedActions: AgentAction[] = [
    {
      id: "act-soc-" + Date.now(),
      agentId: "social",
      title: "Publish Instagram & Facebook Campaign: 'Highveld Summer Protection'",
      description: "Schedule multi-channel social post highlighting Dulux Weathershield 20L with water-resistant demonstration visual across Facebook and Instagram.",
      category: "social_post_publish",
      severity: "low",
      estimatedImpact: "Est. reach 3,400+ targeted local DIYers & 45 contractor inquiries",
      payload: {
        platforms: ["Instagram Feed", "Facebook Page", "Google Business Profile"],
        scheduledTime: "Tomorrow, 08:30 SAST",
        productFocus: "Dulux Weathershield 20L",
        callToAction: "Visit Sandton Store / WhatsApp Trade Desk",
      },
      status: "pending_approval",
      createdAt: new Date().toISOString(),
    },
  ];

  addAgentLog({
    agentId: "social",
    agentName: "Social Media & Engagement Agent",
    level: "info",
    message: "Generated 7-day multi-channel social calendar and drafted Instagram/LinkedIn posts.",
    details: { platformsTargeted: 4, postsDrafted: 3 },
  });

  return {
    agentId: "social",
    agentName: "Social Media & Engagement Agent",
    summary: "Generated a tailored 7-day social media schedule across Instagram, LinkedIn, and Google Business with high-converting creative captions and local SEO keywords.",
    confidenceScore: 96,
    healthStatus: "optimal",
    keyFindings: [
      "Crafted 3 ready-to-publish social posts tailored for trade contractors and retail DIY audiences.",
      "Optimized posting schedule for South African peak engagement windows (08:30 & 11:45 SAST).",
      "Drafted high-intent Google Business Profile post to drive weekend walk-in store foot traffic.",
    ],
    suggestedActions,
    rawInsightsMarkdown: insightsMarkdown,
    timestamp: new Date().toISOString(),
    source,
  };
}
